---

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: types/userparameter.yml
  vars:
    zabbix_agent__userparameter:
      name: orangepi
      comment: Theses items get the hardware information of the Odroid
      userparameters:
        - key: orangepi.cpu.temperature
          command: /bin/bash -c "test -f /sys/class/thermal/thermal_zone0/temp && cat /sys/class/thermal/thermal_zone0/temp || echo -n 'ZBX_NOTSUPPORTED'"
          comment: Get CPU core temperature. exemple "45622" for 45.6 C
        - key: orangepi.cpu.frequency
          command: /usr/bin/env cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
          comment: Get CPU current frequency
          sudo: True
          sudo_user: root
          sudo_group: root
      state: present
  tags: ['odroid', 'odroid-monitoring']
